.TH SHELLY 1 "March 2026" "1.0.0" "User Commands"

.SH NAME
shelly \- command-line libalpm utility

.SH SYNOPSIS
.B shelly
.RI [ OPTIONS ] " <COMMAND>"

.SH DESCRIPTION
shelly is a comand-line interface for managing system packages, 
syncronizing databases, and performing system maintenance tasks. 
It provides functionality similar to traditional package managers 
with extended support for AUR and Flatpak.

.\" This section needs some time. It's important to add every single option there is by default.
.SH OPTIONS
.TP
.B -h, --help
Print help information

.TP
.B -h, --version
Print version information

.\" After this point, there should be information on every command available to shelly.

.SH COMMANDS  

.\" Now, some examples to finish the explanation

.SH EXAMPLES

.\" Finishing with author information
.SH AUTHOR