// Frozen reference files; manifest.json records the source and SHA-256 of each.
pub const files = [_]struct { path: []const u8, bytes: []const u8 }{
    .{ .path = "COPYING", .bytes = @embedFile("COPYING") },
    .{ .path = "alpm_list.h", .bytes = @embedFile("alpm_list.h") },
    .{ .path = "downstream-alpm.h", .bytes = @embedFile("downstream-alpm.h") },
    .{ .path = "downstream-libalpm.diff", .bytes = @embedFile("downstream-libalpm.diff") },
    .{ .path = "downstream-source-tests.tar.gz", .bytes = @embedFile("downstream-source-tests.tar.gz") },
    .{ .path = "meson.build", .bytes = @embedFile("meson.build") },
    .{ .path = "meson_options.txt", .bytes = @embedFile("meson_options.txt") },
    .{ .path = "packaging/.BUILDINFO", .bytes = @embedFile("packaging/.BUILDINFO") },
    .{ .path = "packaging/.PKGINFO", .bytes = @embedFile("packaging/.PKGINFO") },
    .{ .path = "packaging/.SRCINFO", .bytes = @embedFile("packaging/.SRCINFO") },
    .{ .path = "packaging/21b8d8a21a03e0d44294626f7222adda6b48dfac.patch", .bytes = @embedFile("packaging/21b8d8a21a03e0d44294626f7222adda6b48dfac.patch") },
    .{ .path = "packaging/78cd453.patch", .bytes = @embedFile("packaging/78cd453.patch") },
    .{ .path = "packaging/PKGBUILD", .bytes = @embedFile("packaging/PKGBUILD") },
    .{ .path = "packaging/alpm.sysusers", .bytes = @embedFile("packaging/alpm.sysusers") },
    .{ .path = "packaging/disable-always-stale.patch", .bytes = @embedFile("packaging/disable-always-stale.patch") },
    .{ .path = "packaging/fix-alpm-crate-for-aarch64.patch", .bytes = @embedFile("packaging/fix-alpm-crate-for-aarch64.patch") },
    .{ .path = "packaging/makepkg.conf", .bytes = @embedFile("packaging/makepkg.conf") },
    .{ .path = "packaging/pacman.conf", .bytes = @embedFile("packaging/pacman.conf") },
    .{ .path = "packaging/rust.conf", .bytes = @embedFile("packaging/rust.conf") },
    .{ .path = "packaging/static_sqlite.patch", .bytes = @embedFile("packaging/static_sqlite.patch") },
    .{ .path = "upstream-alpm.h", .bytes = @embedFile("upstream-alpm.h") },
    .{ .path = "upstream-source-tests.tar.gz", .bytes = @embedFile("upstream-source-tests.tar.gz") },
};
