using System.CommandLine;
using System.Text;
using System.Text.RegularExpressions;
using Shelly.Cli.Shortcodes;

namespace Shelly.Cli.Commands.Utility;

public static partial class Docs
{
    public static Command Create()
    {
        var command = new Command("docs", "Generate Markdown reference documentation for the Shelly CLI");

        command.SetAction((_, _) =>
        {
            var root = Program.BuildRootCommand();
            var markdown = Generate(root);
            Console.WriteLine(markdown);
            return Task.FromResult(0);
        });

        return command;
    }

    private static string Generate(Command root)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Shelly CLI Documentation");
        sb.AppendLine();
        sb.AppendLine("> Auto-generated by `shelly docs`.");

        WriteSummary(sb, root);

        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();
        WriteShortcodesSection(sb);

        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();

        WriteCommand(sb, root, "shelly", 2, []);

        return sb.ToString().TrimEnd() + Environment.NewLine;
    }

    private static void WriteSummary(StringBuilder sb, Command root)
    {
        sb.AppendLine();
        sb.AppendLine("## Overview");
        sb.AppendLine();
        sb.AppendLine(root.Description);
        sb.AppendLine();

        var direct = root.Subcommands
            .Where(c => c.Subcommands.Count == 0)
            .ToList();

        if (direct.Count > 0)
        {
            sb.AppendLine($"### Direct Commands ({root.Name})");
            sb.AppendLine();
            WriteCommandTable(sb, direct, string.Empty);
        }

        var branches = root.Subcommands
            .Where(c => c.Subcommands.Count > 0)
            .ToList();

        foreach (var branch in branches)
        {
            var heading = string.IsNullOrWhiteSpace(branch.Description)
                ? $"`{root.Name} {branch.Name}`"
                : $"{branch.Description} (`{root.Name} {branch.Name}`)";

            sb.AppendLine($"### {heading}");
            sb.AppendLine();
            WriteCommandTable(sb, branch.Subcommands.ToList(), branch.Name);
        }
    }

    private static void WriteCommandTable(StringBuilder sb, List<Command> commands, string prefix)
    {
        if (commands.Count == 0)
            return;

        var rows = commands.Select(cmd =>
        {
            var signature = string.IsNullOrEmpty(prefix) ? cmd.Name : $"{prefix} {cmd.Name}";
            foreach (var arg in cmd.Arguments)
            {
                var name = arg.Name;
                if (arg.Arity.MaximumNumberOfValues > 1)
                    name += "...";

                var token = arg.Arity.MinimumNumberOfValues > 0 ? $"<{name}>" : $"[{name}]";
                signature += $" {token}";
            }

            return (Cell: $"`{signature}`", Desc: cmd.Description ?? string.Empty);
        }).ToList();

        var commandWidth = Math.Max("Command".Length, rows.Max(r => r.Cell.Length));
        var descriptionWidth = Math.Max("Description".Length, rows.Max(r => r.Desc.Length));

        sb.AppendLine($"| {"Command".PadRight(commandWidth)} | {"Description".PadRight(descriptionWidth)} |");
        sb.AppendLine($"|{new string('-', commandWidth + 2)}|{new string('-', descriptionWidth + 2)}|");
        foreach (var (cell, desc) in rows)
            sb.AppendLine($"| {cell.PadRight(commandWidth)} | {desc.PadRight(descriptionWidth)} |");

        sb.AppendLine();
    }

    private static void WriteCommand(StringBuilder sb, Command cmd, string parentDisplay, int level, IReadOnlyList<Option> inheritedOptions)
    {
        var displayPath = cmd is RootCommand ? "shelly" : $"{parentDisplay} {cmd.Name}".Trim();
        var effectiveOptions = GetEffectiveOptions(cmd, inheritedOptions);
        var heading = new string('#', level);

        sb.AppendLine();
        sb.AppendLine($"{heading} `{displayPath}`");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(cmd.Description))
        {
            sb.AppendLine(cmd.Description);
            sb.AppendLine();
        }

        if (cmd.Subcommands.Count > 0)
        {
            sb.AppendLine("*Branch command — use one of the subcommands below.*");
            sb.AppendLine();
            sb.AppendLine("**Subcommands:**");
            sb.AppendLine();
            foreach (var sub in cmd.Subcommands)
            {
                var subPath = $"{displayPath} {sub.Name}";
                sb.AppendLine($"- [`{subPath}`](#{Anchor(subPath)}) — {sub.Description}");
            }

            sb.AppendLine();
        }

        sb.AppendLine("**Usage:**");
        sb.AppendLine();
        sb.AppendLine("```text");
        sb.AppendLine(BuildUsage(displayPath, cmd, effectiveOptions));
        sb.AppendLine("```");
        sb.AppendLine();

        if (cmd.Arguments.Count > 0)
        {
            sb.AppendLine("| Argument | Arity | Description |");
            sb.AppendLine("|----------|-------|-------------|");
            foreach (var arg in cmd.Arguments)
                sb.AppendLine($"| `<{arg.Name}>` | {FormatArity(arg.Arity)} | {Escape(arg.Description)} |");

            sb.AppendLine();
        }

        if (effectiveOptions.Count > 0)
        {
            sb.AppendLine("| Option | Type | Required | Description |");
            sb.AppendLine("|--------|------|----------|-------------|");
            foreach (var opt in effectiveOptions)
            {
                var aliases = string.Join(", ", opt.Aliases.OrderBy(a => a.Length).Select(a => $"`{a}`"));
                var type = FormatType(opt.ValueType);
                var required = opt.Arity.MinimumNumberOfValues > 0 ? "Yes" : "No";
                sb.AppendLine($"| {aliases} | {type} | {required} | {Escape(opt.Description)} |");
            }

            sb.AppendLine();
        }

        foreach (var sub in cmd.Subcommands)
            WriteCommand(sb, sub, displayPath, level + 1, effectiveOptions);
    }

    private static string BuildUsage(string displayPath, Command cmd, IReadOnlyList<Option> effectiveOptions)
    {
        var parts = new List<string> { displayPath };

        foreach (var arg in cmd.Arguments)
        {
            var name = arg.Name;
            if (arg.Arity.MaximumNumberOfValues > 1)
                name += "...";

            parts.Add(arg.Arity.MinimumNumberOfValues > 0 ? $"<{name}>" : $"[{name}]");
        }

        if (effectiveOptions.Count > 0)
            parts.Add("[options]");

        return string.Join(" ", parts);
    }

    private static List<Option> GetEffectiveOptions(Command cmd, IReadOnlyList<Option> inheritedOptions)
    {
        var result = inheritedOptions.ToList();
        if (result.Count == 0) return result;

        foreach (var opt in cmd.Options
                     .Where(o => !IsBuiltInOption(o))
                     .OrderBy(o => o.Aliases.Min(a => a.Length)))
            if (!result.Any(existing => existing.Aliases.Intersect(opt.Aliases).Any()))
                result.Add(opt);

        return result;
    }

    private static bool IsBuiltInOption(Option option)
    {
        return option.Aliases.Contains("--help") ||
               option.Aliases.Contains("-h") ||
               option.Aliases.Contains("/?") ||
               option.Aliases.Contains("--version");
    }

    private static string FormatArity(ArgumentArity arity)
    {
        if (arity.MinimumNumberOfValues == arity.MaximumNumberOfValues)
            return arity.MinimumNumberOfValues.ToString();

        if (arity.MaximumNumberOfValues == int.MaxValue)
            return arity.MinimumNumberOfValues == 0 ? "0.." : $"{arity.MinimumNumberOfValues}..";

        return $"{arity.MinimumNumberOfValues}..{arity.MaximumNumberOfValues}";
    }

    private static string FormatType(Type type)
    {
        var name = type.Name;
        if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Nullable<>))
            name = type.GetGenericArguments()[0].Name + "?";

        return name switch
        {
            "String" => "string",
            "Int32" => "int",
            "Int64" => "long",
            "Boolean" => "bool",
            "Double" => "double",
            "Single" => "float",
            _ => name.ToLowerInvariant()
        };
    }

    private static string Anchor(string text)
    {
        return AnchorRegex().Replace(text.ToLowerInvariant(), "-").Trim('-');
    }

    private static string Escape(string? text)
    {
        return (text ?? "-").Replace("|", "\\|").Replace("\r\n", " ").Replace("\n", " ").Trim();
    }

    private static void WriteShortcodesSection(StringBuilder sb)
    {
        sb.AppendLine("### Shortcodes");
        sb.AppendLine();
        sb.AppendLine("Grammar: `-<Type><Action><modifiers...>` [positionals]");
        sb.AppendLine();
        sb.AppendLine(
            "Type selects the command group, Action selects the verb, and modifiers are that verb's own short flags (case-sensitive).");
        sb.AppendLine();
        sb.AppendLine("| Type | Group |");
        sb.AppendLine("|------|-------|");

        foreach (var (letter, group) in ShortcodeMaps.Types)
        {
            var name = string.IsNullOrEmpty(group)
                ? letter switch { 'S' => "standard", 'U' => "utility", _ => group }
                : group;
            sb.AppendLine($"| `{letter}`  | {name} |");
        }

        sb.AppendLine();
        sb.AppendLine("Examples:");
        sb.AppendLine();
        sb.AppendLine("```sh");
        sb.AppendLine("-SIu firefox   ->  install -u firefox");
        sb.AppendLine("-AS query      ->  aur search query");
        sb.AppendLine("-KV ABCD       ->  keyring recv ABCD");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("> In shortcode mode use `--ui-mode` instead of `-U`.");
        sb.AppendLine();
        sb.AppendLine("#### Actions by Type");

        foreach (var (typeLetter, group) in ShortcodeMaps.Types)
        {
            var typeName = string.IsNullOrEmpty(group)
                ? typeLetter switch { 'S' => "standard", 'U' => "utility", _ => group }
                : group;

            sb.AppendLine();
            sb.AppendLine($"**`{typeLetter}` — {typeName}**");
            sb.AppendLine();

            if (typeLetter == 'K')
            {
                sb.AppendLine("| Action | Verb |");
                sb.AppendLine("|--------|------|");
                foreach (var (actionLetter, verb) in ShortcodeMaps.KeyringActions)
                    sb.AppendLine($"| `{actionLetter}` | {verb} |");
            }
            else
            {
                var actions = ShortcodeMaps.Actions
                    .Where(kv => kv.Key.Item1 == typeLetter)
                    .ToList();

                if (actions.Count == 0)
                    continue;

                sb.AppendLine("| Action | Verb | Modifiers |");
                sb.AppendLine("|--------|------|-----------|");
                foreach (var kv in actions)
                {
                    var actionLetter = kv.Key.Item2;
                    var verb = kv.Value;
                    var modifiers = ShortcodeMaps.Modifiers.TryGetValue(kv.Key, out var mods) && mods.Count > 0
                        ? string.Join(", ", mods.Order().Select(m => $"`{m}`"))
                        : "—";
                    sb.AppendLine($"| `{actionLetter}` | {verb} | {modifiers} |");
                }
            }
        }
    }

    [GeneratedRegex(@"[^a-z0-9\-]+")]
    private static partial Regex AnchorRegex();
}